### ISSUE TITLE
needs more disambiguation for difference b/w `adapter_name`, `directory_name` and `project_name`

### ISSUE THREAD

**Issue by dataders** [dbt-labs/dbt-database-adapter-scaffold#32]
## Problem
I gave a project the name of `dbt-mongodb`, so then `adapter_name = 'dbt-mongodb'`. so then the template got filled out to be like this

<img width="341" alt="image" src="https://user-images.githubusercontent.com/8158673/165176702-c8bacf76-33ac-4ff8-b7ed-cecd8b83d1fc.png">

https://github.com/dbt-labs/dbt-database-adapter-scaffold/blob/20bcb9a2204a9c6d76b7a4d964a3920a67796492/%7B%7Bcookiecutter.project_name%7D%7D/dbt/adapters/%7B%7Bcookiecutter.directory_name%7D%7D/connections.py#L13

https://github.com/dbt-labs/dbt-database-adapter-scaffold/blob/ad3a9855631d50f301214d797e9f379c956514fc/cookiecutter.json#L5

https://github.com/dbt-labs/dbt-database-adapter-scaffold/blob/20bcb9a2204a9c6d76b7a4d964a3920a67796492/hooks/pre_gen_project.py#L2

## Solution

Given [cookiecutter's docs on templates in context values](https://cookiecutter.readthedocs.io/en/2.0.2/advanced/templates_in_context.html) IMHO it makes sense to turn `adapter_name`, `directory_name` and `project_name` into a single prompt like:
> What is the name of your database in CamelCase? `MongoDB`
from that we get:
```
adapter_name in CamelCase [MongoDB]: MongoDB
directory_name [adapter_name.lower()]: mongodb
project_name [dbt-{directory_name}]: dbt-mongodb
description [the {adapter_name} adapter plugin for dbt.]: 
```

**Comment by McKnight-42** [comment]
@dataders opened up #33 in regards to this during making up the json i've tried to find find more and more ways to cut out repetitive or unneeded things that could be passed down to pre_gen hooks so they don't need to be in the prompt sadly the `project_name` has to stay in json as it is needed to populate very fast to take place in primary directory for generated folder. was able to make some headway in cutting down some of the prompt clutter by letting things like description be what they truly were and just a string interpolation after generation not seen by user, and allowing for some duplication of code in regards to how we handle naming of `project_name` and `directory_name` so one can be hidden in the hooks.

**Comment by McKnight-42** [comment]
Really fill like we were able to drill down deep into this to clear out unnecessary interactive session and provide what I hope is a good user experience.
